app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');


Route::get('/admin',function(){
return view('admin.index');
});

Route::group(['middleware' => 'admin'], function () {
    
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $fillable=[
        'title',
        'body',
        'category_id',
        'photo_id',
        

    ];

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function photo(){
        return $this->belongsTo('App\Photo');
    }

    public function category(){
        return $this->belongsTo('App\Category');
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')



@section('content')

<h1>Create Post</h1>

{!! Form::open(['method' => 'POST','action' => 'AdminPostsController@store', 'files'=>true]) !!}

<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('category_id', 'Category:') !!}
    {!! Form::select('category_id',[''=>'Choose Categories'] + $categories ,null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('photo_id', 'Photo:') !!}
    {!! Form::file('photo_id',null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('body', 'Description:') !!}
    {!! Form::textarea('body', null, ['class'=>'form-control']) !!}
</div>


<div class="form-group">
    {!! Form::submit('Create  Post', ['class'=>'btn btn-primary']) !!}

</div>


{!! Form::close() !!}
@include('includes.form_error')


@stop

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')



@section('content')

<h1>Edit Post</h1>
<div class="col-sm-3"> 
        <img src="{{$post->photo ? $post->photo->file :'https://via.placeholder.com/400/#000
        
        C/O https://placeholder.com/' }}" alt="" class="img-responsive rounded-circle ">
        
        
        </div>



<div class="col-sm-9">

{!! Form::model( $post,['method' => 'PATCH','action' => ['AdminPostsController@update', $post->id], 'files'=>true]) !!}

<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('category_id', 'Category:') !!}
    {!! Form::select('category_id', $categories ,null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('photo_id', 'Photo:') !!}
    {!! Form::file('photo_id',null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('body', 'Description:') !!}
    {!! Form::textarea('body', null, ['class'=>'form-control']) !!}
</div>


<div class="form-group">
    {!! Form::submit('Update Post', ['class'=>'btn btn-primary col-sm-6' ]) !!}
    

</div>




{!! Form::close() !!}
<div class="form-group">

{!! Form::open(['method' => 'DELETE','action' => ['AdminPostsController@destroy',$post->id]]) !!}
        
{!! Form::submit('Delete Post', ['class'=>'btn btn-danger  col-sm-6']) !!}

{!! Form::close() !!}
</div>
@include('includes.form_error')


@stop

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')



@section('content')

@if(Session::has('deleted_post'))
<p class="alert alert-success">{{session('deleted_post')}}</p>

@endif

<h1>Posts</h1>

<table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Photo</th>
        <th>Owner</th>
        <th>Category</th>
        
        <th>Title</th>
        <th>Body</th>
        
        <th>Created_at</th>
        <th>Updated_at</th>
      </tr>
    </thead>
    <tbody>
        @if($posts)
        @foreach($posts as $post)
      <tr>
      <td>{{$post->id}}</td>
      <td><img height="60" src="{{$post->photo ? $post->photo->file : 'https://via.placeholder.com/400/#000

        C/O https://placeholder.com/'}} " alt=""></td>
      <td><a href="{{route('admin.posts.edit', $post->id)}}">{{$post->user->name}}</a></td>
      <td>{{$post->category? $post->category->name : 'Uncategorized'}}</td>
     
      <td>{{$post->title}}</td>
      <td>{{ str_limit($post->body), 20}}</td>
      
        <td>{{$post->created_at->diffForHumans()}}</td>
        <td>{{$post->updated_at->diffForHumans()}}</td>
      </tr>
      @endforeach
      @endif
      
    </tbody>
  </table>



@stop