app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');


Route::get('/admin',function(){
return view('admin.index');
});

Route::group(['middleware' => 'admin'], function () {
    
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
     protected $fillable = ['name'];
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')


@section('content')


<h1>Categories</h1>
<div class="col-sm-6">
        {!! Form::model($category,['method' => 'PATCH','action' => ['AdminCategoriesController@update',$category->id]]) !!}

        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class'=>'form-control']) !!}
        </div>
        
       

        <div class="form-group">
                {!! Form::submit('Update', ['class'=>'btn btn-primary col-sm-6']) !!}
            
            </div>
            
            
            {!! Form::close() !!}

            {!! Form::model($category,['method' => 'DELETE','action' => ['AdminCategoriesController@destroy',$category->id]]) !!}


            <div class="form-group">
                
            {!! Form::submit('Delete', ['class'=>'btn btn-danger col-sm-6']) !!}

            </div>
                    
            {!! Form::close() !!}
            
            @include('includes.form_error')
            
            
            
       
   


</div>
<div class="col-sm-6">




</div>
@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')


@section('content')
@if(Session::has('updated_category'))
<p class="alert alert-success">{{session('updated_category')}}</p>

    

    
@else
<p class="alert alert-success">{{session('deleted_category')}}</p>
    
@endif
    





<h1>Categories</h1>
<div class="col-sm-6">
        {!! Form::open(['method' => 'POST','action' => 'AdminCategoriesController@store', 'files'=>true]) !!}

        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class'=>'form-control']) !!}
        </div>
        
       

        <div class="form-group">
                {!! Form::submit('Create Category', ['class'=>'btn btn-primary']) !!}
            
            </div>
            
            
            {!! Form::close() !!}
            
            @include('includes.form_error')
            
            
            
       
   


</div>

<div class="col-sm-6">
        @if ($categories)
        
    
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Created Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category )
                    
                
                <tr>
                <td>{{$category->id}}</td>
                    <td><a href="{{route('admin.categories.edit',$category->id)}}">  {{$category->name}}</a></td>
                <td>{{$category->created_at? $category->created_at->diffForHumans() : 'Unspecified date'}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    
            @endif  


</div>

    
@endsection